name: PR Checks
on: pull_request
jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Code Checks
        run: ./gradlew check
